# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestprodusebranduri():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testprodusebranduri(self):
    # Test name: test produse branduri
    # Step # | name | target | value
    # 1 | open | /ro/ | 
    self.driver.get("http://34.118.122.203/ro/")
    # 2 | setWindowSize | 1920x1040 | 
    self.driver.set_window_size(1920, 1040)
    # 3 | click | css=a > .hidden-sm-down | 
    self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
    # 4 | click | id=field-email | 
    self.driver.find_element(By.ID, "field-email").click()
    # 5 | type | id=field-email | maricaandrei60@gmail.com
    self.driver.find_element(By.ID, "field-email").send_keys("maricaandrei60@gmail.com")
    # 6 | type | id=field-password | octopussy581A
    self.driver.find_element(By.ID, "field-password").send_keys("octopussy581A")
    # 7 | click | id=submit-login | 
    self.driver.find_element(By.ID, "submit-login").click()
    # 8 | click | css=#category-10 > .dropdown-item | 
    self.driver.find_element(By.CSS_SELECTOR, "#category-10 > .dropdown-item").click()
    # 9 | click | css=.js-product:nth-child(2) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
    # 10 | click | css=.img | 
    self.driver.find_element(By.CSS_SELECTOR, ".img").click()
    # 11 | click | css=.js-product:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
    # 12 | click | css=.add-to-cart |
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 13 | click | css=.cart-content-btn > .btn-secondary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # 14 | click | css=.img | 
    self.driver.find_element(By.CSS_SELECTOR, ".img").click()
    # 15 | click | css=.js-product:nth-child(2) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
    # 16 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 17 | click | css=.cart-content-btn > .btn-secondary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # 18 | click | css=.img | 
    self.driver.find_element(By.CSS_SELECTOR, ".img").click()
    # 19 | click | css=.js-product:nth-child(3) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(3) img").click()
    # 20 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 21 | click | css=.cart-content-btn > .btn-secondary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # 22 | click | css=#category-15 > .dropdown-item | 
    self.driver.find_element(By.CSS_SELECTOR, "#category-15 > .dropdown-item").click()
    # 23 | click | css=.js-product:nth-child(2) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
    # 24 | click | css=.img | 
    self.driver.find_element(By.CSS_SELECTOR, ".img").click()
    # 25 | click | css=.js-product:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
    # 26 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 27 | click | css=.cart-content-btn > .btn-secondary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # 14 | click | css=a:nth-child(1) > .hidden-sm-down |
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .hidden-sm-down").click()
    produse = self.driver.find_elements(By.CLASS_NAME, "cart-item")
    if len(produse) > 0:
      print("Produsele selectionate dupa brand sunt in cos")
    else:
      print("Test nereusit")
    # # 28 | click | css=.img |
    # self.driver.find_element(By.CSS_SELECTOR, ".img").click()
    # 29 | click | css=.js-product:nth-child(2) img |
    # self.driver.implicitly_wait(3)
    # self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
    # # 30 | click | css=.add-to-cart |
    # self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # # 31 | mouseOver | css=.img |
    # element = self.driver.find_element(By.CSS_SELECTOR, ".img")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # # 32 | mouseOut | css=.img |
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element_with_offset(element, 0, 0).perform()
    # # 33 | click | css=.cart-content-btn > .btn-secondary |
    # self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # # 34 | mouseUp | css=.img |
    # element = self.driver.find_element(By.CSS_SELECTOR, ".img")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).release().perform()
    # # 35 | click | css=.js-product:nth-child(1) img |
    # self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
    # # 36 | click | css=.add-to-cart |
    # self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # # 37 | click | css=.cart-content-btn > .btn-primary |
    # self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary").click()
    # # 38 | click | css=.text-sm-center > .btn |
    # self.driver.find_element(By.CSS_SELECTOR, ".text-sm-center > .btn").click()
    # # 39 | click | name=confirm-addresses |
    # self.driver.find_element(By.NAME, "confirm-addresses").click()
    # # 40 | click | name=confirmDeliveryOption |
    # self.driver.find_element(By.NAME, "confirmDeliveryOption").click()
    # # 41 | click | id=conditions_to_approve[terms-and-conditions] |
    # self.driver.find_element(By.ID, "conditions_to_approve[terms-and-conditions]").click()
    # # 42 | click | css=.ps-shown-by-js > .btn |
    # self.driver.find_element(By.CSS_SELECTOR, ".ps-shown-by-js > .btn").click()
  
