# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAdaugareprodus():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testprodusmarimeXL(self):
        # Test name: test produs marime XL
        # Step # | name | target | value
        # 1 | open | /ro/ |
    self.driver.get("http://34.118.122.203/ro/")
        # 2 | setWindowSize | 1900x1020 |
    self.driver.set_window_size(1900, 1020)
        # 3 | click | css=a > .hidden-sm-down |
    self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
        # 4 | click | id=field-email |
    self.driver.find_element(By.ID, "field-email").click()
        # 5 | type | id=field-email | maricaandrei60@gmail.com
    self.driver.find_element(By.ID, "field-email").send_keys("maricaandrei60@gmail.com")
        # 6 | type | id=field-password | octopussy581A
    self.driver.find_element(By.ID, "field-password").send_keys("octopussy581A")
        # 7 | click | id=submit-login |
    self.driver.find_element(By.ID, "submit-login").click()
    self.driver.get("http://34.118.122.203/en/")
    self.driver.implicitly_wait(3)
        # 3 | click | css=.featured-products:nth-child(4) .js-product:nth-child(1) img |
    self.driver.find_element(By.CSS_SELECTOR, ".featured-products:nth-child(4) .js-product:nth-child(1) img").click()
        # 4 | click | css=.featured-products:nth-child(4) .js-product:nth-child(8) img |
    self.driver.find_element(By.CSS_SELECTOR, ".featured-products:nth-child(4) .js-product:nth-child(8) img").click()
        # 5 | click | css=.add-to-cart |
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        # 6 | click | css=.cart-content-btn > .btn-secondary |
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        # 7 | click | css=.header .hidden-sm-down |
    self.driver.find_element(By.CSS_SELECTOR, ".header .hidden-sm-down").click()
        # 8 | click | css=.cart-item:nth-child(2) .col-md-2 .material-icons |
    self.driver.find_element(By.CSS_SELECTOR, ".cart-item:nth-child(2) .col-md-2 .material-icons").click()
        # 9 | click | css=.cart-grid |
    self.driver.find_element(By.CSS_SELECTOR, ".cart-grid").click()
    assert 'Hummingbird printed t-shirt' in self.driver.page_source


